version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m     
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn clean
      - run: mvn test -s settings.xml
      - run: mvn package -s settings.xml
      - run: mvn install -s settings.xml
      - run: 
          case $CIRCLE_BRANCH in 
            'master') export environment='Sandbox';;
            'develop') export environment='Sandbox';;
          esac; 
          echo $environment; 
          mvn mule:deploy -Dworkers=0.1 -DworkerType=Micro -Denvironment=$environment -Dredeploy=true -DmuleVersion=3.9.0 -s settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}